### ISSUE TITLE
Housenumber

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#106]
The housenumber isn't saved after adding from list (autocomplete).
(after go to step 3 from wizard, then back to 2 OR hit save and then F5)

![image](https://user-images.githubusercontent.com/46600362/71784872-d333be80-2ff8-11ea-9afc-9ceef95f7f95.png)

**Comment by yorickdewid** [comment]
Neither streetname nor street number is saved, only the BAG code. Should have a service to translate back to visible name. Not a bug, but improvement

**Comment by DonZandbergen** [comment]
Not fixxed:

![image](https://user-images.githubusercontent.com/46600362/71920854-f6d93f00-3187-11ea-999e-443392762d5a.png)
