### ISSUE TITLE
Wizard step 1 to 2 error 400

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#127]
In wizard from step 2 to step 1,
Then back to step 2 ("volgende") gives error 400

![image](https://user-images.githubusercontent.com/46600362/72097474-c1198f00-331c-11ea-896e-f273b76494e5.png)

**Comment by yorickdewid** [comment]
Cannot reproduce

**Comment by yorickdewid** [comment]
Report Id?

**Comment by yorickdewid** [comment]
Document is required, not all reports contain documents
