### ISSUE TITLE
Error access control incident (loket.kcaf.nl)

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#150]
https://loket.kcaf.nl/#/ won't submit form in last step "send" due to access control incident:
 
![image](https://user-images.githubusercontent.com/46600362/76348647-d6a13a00-6308-11ea-83f1-69dfc23cd993.png)

**Comment by yorickdewid** [comment]
Bljkt een CORS probleem

**Comment by yorickdewid** [comment]
Fix comitted and pushed later if issue is resolved
