### ISSUE TITLE
Zakkingsdata Woonborg

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#152]
Pandzakkingsanalyses o.b.v. Remote Monitoring (satelliet-data) van Sensar (vergelijkbaar met data account Schiedam)

- Data uploaden voor account woonborg (Geofence)
- Zelfde schaalverdeling als account Schiedam aanhouden (kan ook niet anders)
- C:\Users\Donza\OneDrive\BEDRIJVEN\fundermapsbv_projecten\DATA\zakkingsdata_woonborg
- Tevens kaartlaag inladen met zakking van de subbuurt, zelfde kleurverdeling (@yorickdewid 
 is deze aanwezig in de zip?)

**Comment by DonZandbergen** [comment]
Graag reactie wanneer GeoPackage te gebruiken is, dan neem ik geen contact op met Sensar.

**Comment by yorickdewid** [comment]
Done
