### ISSUE TITLE
Zakkingsdata Haarlem

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#154]
Pandzakkingsanalyses o.b.v. Remote Monitoring (satelliet-data) van SkyGeo (vergelijkbaar met data account Rotterdam)

Data uploaden voor account Haarlem (Geofence)
Zelfde schaalverdeling als account Schiedam aanhouden (kan ook niet anders)

C:\Users\Donza\Laixer\FunderMaps - Documenten\General\WebApplication\Data\zakkingsdata_haarlem

Tevens kaartlaag inladen met zakking van de wijk, zelfde kleurverdeling

**Comment by yorickdewid** [comment]
BAG_id ontbreekt
