### ISSUE TITLE
Tekst aanpassingen loket

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#155]
Tekstaanpassingen:
[Wie zijn wij.docx](https://github.com/Laixer/FunderMaps/files/4452616/Wie.zijn.wij.docx)

Achtergrond plaatje aanpassing:
![27_funderingsherstel](https://user-images.githubusercontent.com/46600362/78829607-ef277180-79e6-11ea-9394-7ed9d1a1d5ce.jpg)

**Comment by yorickdewid** [comment]
Done
