### ISSUE TITLE
GeoFence Dordrecht / KCAF

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#159]
Replace current Geofence in account KCAF with:

4.6715927, 51.8218268
4.6515942, 51.8124355
4.6442127, 51.8051121
4.6575165, 51.7943902
4.6740818, 51.7979468
4.6792316, 51.7953988
4.7030067, 51.8083494
4.6715927, 51.8218268
{
  "coordinates": [
    [
      [
        4.6715927,
        51.8218268
      ],
      [
        4.6515942,
        51.8124355
      ],
      [
        4.6442127,
        51.8051121
      ],
      [
        4.6575165,
        51.7943902
      ],
      [
        4.6740818,
        51.7979468
      ],
      [
        4.6792316,
        51.7953988
      ],
      [
        4.7030067,
        51.8083494
      ],
      [
        4.6715927,
        51.8218268
      ]
    ]
  ],
  "type": "Polygon"
}

**Comment by yorickdewid** [comment]
@tabeckers `SELECT application.set_organization_fence(..)`

**Comment by tabeckers** [comment]
Updated geofence in database
