### ISSUE TITLE
Export panden/adressen

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#160]
Maak export (.shp of GeoJson) vanuit onze FM BAG database voor het contour van het account van Woonbron, waarin per pandID alle adresnummers zijn bijgevoegd.

**Comment by yorickdewid** [comment]
Depends on #175

**Comment by yorickdewid** [comment]
Function ready, exec when db is ready

**Comment by tabeckers** [comment]
All premises in the geofence for Woonbron were exported and added to a shapefile.
