### ISSUE TITLE
Database product creation

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMaps#163]
This issue represents the process of being able to retrieve each product from our database. The approach will probably be done using a view for each product.

The following analysis fields have to be included in our products (some of which we already have):
- [x] Foundation type
- [x] Groundwater level
- [x] Foundation risk
- [x] Construction year
- [x] Building height
- [x] Ground level
- [x] Estimated restoration costs
- [x] Dewatering depth (no-pile foundation types)
- [x] Drystand (wooden foundation types)
- [x] Reliability of data

The following statistics fields have to be included in our products:
- [x] Foundation type ratio
- [x] Construction years per decennia
- [x] Ratio foundation risk
- [x] Data collected percentage
- [x] Total buildings restored
- [x] Total incidents reported
- [x] Total inquiries

**Comment by tabeckers** [comment]
@DonZandbergen How are we going to calculate the estimated restoration costs of a building?

**Comment by tabeckers** [comment]
**Drystand & dewatering depth**
We will only show one of these, depending on the type of foundation.
If we have a report for a building, we calculate the drystand as following:
- _Wooden foundation types_: `drystand = wood_level - groundwater_level`
- _No-pile foundation types_: `dewatering depth = foundation_depth - groundwater_level`
If no report is present:
- `drystand = groundwater_level - 60cm`

**Estimated restoration costs**
Depending on the type of foundations, the costs are calculated as follows:
- _Wooden foundation types:_ `area * 950€`
- _No-pile foundation types_: `area * 350€`

**Reliability**
If a report exists for a building we indicate the reliability as `established`. If not, we indicate the reliability as `indicative`.

**Comment by tabeckers** [comment]
@DonZandbergen with regards to the **Drystand & Dewatering Depth**, which of the three possible calculations (listed in my previous comment) should be used for the following foundation types?
- `concrete`
- `weighted_pile`
- `combined`
- `steel_pile`

**Comment by DonZandbergen** [comment]
> If no report is present:
> 
> * _All foundation types_: `drystand = groundwater_level - 60cm`

Shoukd be:

- Wooden foundation types: drystand = groundwater_level -150cm
- No-pile foundation types: dewatering depth = groundwater_level - 60cm

**Comment by DonZandbergen** [comment]
> **Drystand & dewatering depth**
> We will only show one of these, depending on the type of foundation.
> If we have a report for a building, we calculate the drystand as following:

Add the follow to Drystand & dewatering depth:

- Other (* 'concrete', * 'weighted_pile', * 'combined',  *'steel_pile') returns 'null'.

**Comment by DonZandbergen** [comment]
> 1. With regards to the **Drystand & Dewatering Depth**, which of the three possible calculations (listed in my previous comment) should be used for the following foundation types?

See previous comment

**Comment by DonZandbergen** [comment]
> 2. With regards to the **Estimated Restoration Costs**, how will we calculate this value for the following foundation types?
> 
> * `concrete`
> * `weighted_pile`
> * `combined`
> * `steel_pile`

For these foundationtypes we will retun `null` for the **Estimated Restoration Cost** 
(no restoration required for these foundationtypes)

**Comment by DonZandbergen** [comment]
Furthermore: the `foundationtype `in a sample (part of report) must be checked, not whether a report exists.
Otherwise this will go wrong because a report contains n samples (addresses). Foundationtypes can differ for each sample within a report..

**Comment by tabeckers** [comment]
Multiple samples from report -> take latest
