### ISSUE TITLE
Add pandzakkingsdata to the database of FunderMaps prod

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#170]
Bring `fundermaps_development.data.subsidence` to production env. This should be done with the old table style. +old BAG Id.

**Comment by tabeckers** [comment]
The following queries have to be checked after this implementation:

https://github.com/Laixer/FunderMaps/blob/e1c299b7f09617eb8eded2ec6f5b7857a8717640/src/FunderMaps.WebApi/Data/Repositories/MapRepository.cs

**Comment by tabeckers** [comment]
- [ ] Created table 
- [ ] Migrated data
- [ ] Validated data
- [ ] Tested existing queries
