### ISSUE TITLE
FTS search improvement

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMaps#177]
The FTS for addresses in our geocoder.building table works like a charm, but only most of the times. The following cases should be improved:

- [ ] The exact match of the query should always have the highest ranking
- [ ] Postal codes with a space (e.g. 2611 CD or 2611 C D) aren't considered by the algorithm
- [ ] Not every variant of housenumber with a dash ("-") and other kind of symbols are considered by the algorithm
- [ ] The overload of the tsquery function needs some debugging
- [ ] Test cases
- [ ] Single character searches take relatively long
- [ ] Double character searches take relatively long

**Comment by yorickdewid** [comment]
Via PDOK
