### ISSUE TITLE
Remove invalid large geometries from our dataset

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMaps#178]
The BAG (and thus our geocoder.building table) contains some invalid geometries with areas the size of entire municipalities. These obviously have to be filtered out and removed. 

A possible solution could be to replace the geometries with data from OSM or some other datasource.

**Comment by yorickdewid** [comment]
Maybe should do this in GDAL driver?

**Comment by tabeckers** [comment]
The next step will be to compare the surface area from the VBO (verblijfsobject) BAG table with the calculated surface area of the PND (pand) BAG table geometry. If these mismatch beyond some error margin we can declare the geometry as invalid.

A caveat of this approach would be that the BAG might calculate the surface area in the VBO table on the same way as mentioned above, leaving us with no extra information.

**Comment by yorickdewid** [comment]
> A caveat of this approach would be that the BAG might calculate the surface area in the VBO table on the same way as mentioned above, leaving us with no extra information.

Either that or there is just as much invalid data/NULL in this perimeter dataset.

Anyway, this will be the last attempt at fixing these polygons in this milestone.

**Comment by tabeckers** [comment]
The 20 invalid geometries have been set to null. A null constraint for the geocoder.building table was also removed to allow this operation. Dropping this null constraint makes sense, since we can't guarantee that we will always have geometry data for a building.

The following query was executed:
```
UPDATE geocoder.building AS b
SET geom = NULL
WHERE id = 'gfm-cf2ebc5ccfef4d679b21aa9bb79172c5' -- Verticaal
OR id = 'gfm-0170cabf3cec441a94a3e6dc2ad3b72d' -- Horizontaal
OR id = 'gfm-8bff3ffca49f414bbcca3104ae0c3d98' -- Weert
OR id = 'gfm-98348d265e524467a613dc3fb088bd65' -- Weert
OR id = 'gfm-033766b97c46422c982025c61a2f2ce5' -- Weert
OR id = 'gfm-7fcdfaaa3ab6494fabc2a8fa027dfda7' -- Weert
OR id = 'gfm-53104f738e054b3bb570d57a39362181' -- Weert
OR id = 'gfm-73f6b27b3ba54fcca868ffb7114bf211' -- Weert
OR id = 'gfm-2594954705a94746824f4cd2f21faf7b' -- Weert
OR id = 'gfm-3331234e32e744de8fbd40b58592e300' -- Weert
OR id = 'gfm-404aaee0f61e4fd19c6c4cdb7ca3773f' -- Gekke rechte hoek
OR id = 'gfm-0b8abf62b6634bc28539d389c663f4fe' -- Reeuwijk
OR id = 'gfm-fbfbc76fcaa5406ba9430b24be777244' -- Haren
OR id = 'gfm-7996029002204dccac5e14771b359f72' -- Haren
OR id = 'gfm-4b0916633e95413b9bf176617b444bff' -- Haren
OR id = 'gfm-76a997c08326476a8f7117a127595aa6' -- Haren
OR id = 'gfm-f140983b56894123972d91742ffb5968' -- Haren
OR id = 'gfm-f140983b56894123972d91742ffb5968' -- Haren
OR id = 'gfm-91c0d4ac2e454b17a4ebd9f4644816ae' -- Haren
OR id = 'gfm-8dda178cc7c84545bb0912c701c1d259' -- Hyrdegaryp
OR id = 'gfm-38bc6e151039456ba15aad85c59fa52d' -- Hyrdegaryp
```
