### ISSUE TITLE
Deeper analysis of STA and LIG in the BAG

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMaps#180]
The STA and LIG tables in the BAG 2.0 extract have simply been added to the geocoder table. These tables require further analysis to fully understand their contents.

**Comment by tabeckers** [comment]
The BAG contains the following tables which are of interest for building type determination:
- `STA`
- `LIG`
- `PAND`

In general, the `STA` table contains mobile homes, the `LIG` tabale contains houseboats and the `PAND` tables contains houses and sheds. We would like to be able to differentiate between these types of buildings and any other types of buildings which exist in the tables. The BAG itself has no way of specifying the building type other than through the mentioned tabled. The goal is to be able to specify each building type for all data in these tables.

Currently, the `building_type` enum exists in our `geocoder.building` table. This was added after discussion with @yorickdewid when the `STA`, `LIG` and `PAND` tables were all converted and inserted into `geocoder.building`. The following values were set for the `building_type` column in `geocoder.building`:

- `STA` --> `mobile_home`
- `LIG` --> `house_boat`
- `PAND` --> `null`

**Comment by yorickdewid** [comment]
Move into #181
