### ISSUE TITLE
Invalid building number format in geocoder.address

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMaps#183]
The geocoder.address table contains a messy format for the building numbers. Because we extract building numbers from three columns out of the BAG, being _number_, _letter_ and _addon_, some format had to be applied. At the moment the format is these three items appended to each other with a _space_ in between.

This should be done more elegantly because this seems error prone.

**Comment by yorickdewid** [comment]
Do whatever needs to be done, no need to consider FTS
