### ISSUE TITLE
Webservice Intgration tests

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMaps#184]
Integration tests should be created for the following:
- [x] Request analysis product by id
- [x] Request analysis product by bagid
- [x] Request analysis product by query
- [x] Invalid requests for analysis
- [x] Request statistics product by neighborhood code
- [x] Invalid requests for statistics

For our mapping, a separate issue was created (#233).

**Comment by yorickdewid** [comment]
See #5
