### ISSUE TITLE
Authentication integration with ASP.NET Core Security

### ISSUE THREAD

**Issue by yorickdewid** [Laixer/FunderMaps#186]
Integrate FunderMaps core authentication with ASP.NET Core.

- [x] Integrate with `System.Security`
- [x] Integrate with `ISecurityTokenProvider`
- [x] Build authentication manager
- [x] Build authentication provider

Move all common authentication components into the core. Other services should be available for all ASP.NET Core applications

**Comment by tabeckers** [comment]
Removed `checkIfAuthenticated` functionality for the `AuthManager`.
