### ISSUE TITLE
Populate materialized views

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMaps#194]
Our fundermaps_development.data materialized views have to be repopulated. This operation will take a long time (a few days probably) and locks the tables. The following materialized views have to be refreshed with data:

- [x] Materialized view for premise * geographic region
- [x] Materialized view for premise * groundwater level
- [x] Materialized view for foundation type estimation
- [x] Materialized view for foundation risk estimation

When computation has completed, we can execute the following tasks:

- [x] Compare `data.building_geographic_region` with `data.premise_geographic_region_old`
- [x] Compare `data.building_groundwater_level` with `data.premise_groundwater_level_old`
- [x] Drop `data.premise_geographic_region_old`
- [x] Drop `data.premise_groundwater_level_old`

**Comment by yorickdewid** [comment]
Lock is readonly

**Comment by tabeckers** [comment]
The ownership should be changed to fundermaps_development as they are now owned by thomas.

**Comment by tabeckers** [comment]
These operations are computed in a VM instead of the database. Computing these material views in the database takes multiple days, claims too many resources and locks any operations related to the materialized views.

**Comment by tabeckers** [comment]
Additional tasks for comparison with the old tables were added, including dropping the old tables when said comparison is deemed valid.
