### ISSUE TITLE
Polymorphic json data binding

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMaps#198]
Our response models for the Webservice are polymorphic. ASP does not understand this and messes up the mapping. This has to be solved.

**Comment by tabeckers** [comment]
Consider the following situation:

```
public class ResponseWrapper<TModel>
   where TModel : MyModelBase
{
   public TModel AssignedModel { get; set; }
}

public class MyModelBase
{
   public string BaseProperty { get; set; }
}

public class MyModelImplementation : MyModelBase
{
   public string ImplementationProperty { get; set; }
}
```

The ASP.Net Core built in JSON mapper does not map ```ResponseWrapper<MyModelImplementation>``` properly when a ```ResponseWrapper<MyModelBase>``` is returned, having an instance of ```MyModelImplementation``` assigned to its ```AssignedModel``` property. In this case, the mapper will always treat the ```AssignedModel``` property as an instance of ```MyModelBase``` and never as an instance of ```MyModelImplementation```. This means that the ```ImplementationProperty``` will not be mapped to a JSON response object and will disappear completely.

The solution is to introduce a non-generic base class for the response wrapper and make the ```ResponseWrapper<TModel>``` inherit from this base class. When returning an instance of the non-generic ```ResponseWrapper``` our JSON conversion works like a charm.

```
public class ResponseWrapper { }

```



This has been implemented in our Webservice, hence the issue has been solved.

**Comment by yorickdewid** [comment]
- ASP.NET Core does not have a JSON serializer, that thing is part of .NET Core.

- This is expected behaviour for all static cast. Generics are not inheritances and cannot be upcasted in which case the cast turns into a static cast, Generics are diagonal polymorphs (and they're not even full polymorphs as in C++.)
