### ISSUE TITLE
Apply address foreign keys to new reports in FM Production DB

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMaps#202]
This issue is the restoring follow-up action of issue #95. The part of these 16k addresses which were linked to an actual address id should be updated in the FunderMaps production database. A backup will be created before any changes are made.

This is also related to #175. These "missing" addresses do exist in the database, as shown in #175.

**Comment by DonZandbergen** [comment]
It relates to the samples. Which are linked to report.

**Comment by yorickdewid** [comment]
Example samples for testing?

**Comment by DonZandbergen** [comment]
> Example samples for testing?

![image](https://user-images.githubusercontent.com/46600362/89406862-159fb400-d71e-11ea-8b83-7e103d9aa261.png)
(all adresses in the Marconistraat (southside) should have a filled in value for foundationtype)

**Comment by yorickdewid** [comment]
Sample IDs?

**Comment by tabeckers** [comment]
It appears to be the case that the restored address entries contain bagid duplicates. At the moment a unique index exists for the bagid field of the to-be-restored ```application.address``` table. The following steps will be executed at a non-critical moment in time:

- [ ] Remove the unique index
- [ ] Execute an bagid update query based on the restored bagids
- [ ] Create a non-unique index
- [ ] Test
