### ISSUE TITLE
Move tables from data to geocoder and add internal id's

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMaps#209]
Some tables in the ```data``` schema should be in the ```geocoder``` schema. The following tables will be <i>moved, given internal id's and foreign-keyd to each other</i>:

- [x] ```data.country```
- [x] ```data.municipality```
- [x] ```data.district```
- [x] ```data.neighborhood```

Their external id format will match that of the ```geocoder.address``` and ```geocoder.building``` tables.

When everything has been migrated the old tables can be dropped.
- [x] Drop old tables

When migration is complete, each ```geocoder.building``` item will have a new column with a **nullable foreign key** referencing ```geocoder.neighborhood```. This process will be referenced in issue #214.

**Comment by tabeckers** [comment]
Some municipalities contain two entries with the same code in the CBS ```municipalities``` table - one for land and one for water. In our ```geocoder``` tables we want a single entry for each municipality, paired with a single geometry. The current solution is to use ```st_union()``` to combine the water and land geometries into a single ```MULTIPOLYGON```.

**Comment by yorickdewid** [comment]
There is a very unlikely possibly for an object to be not selected by the otherwise corresponding district. Most of our operations calculate the intersection between an object and the geometry, which can leave out items because the majority of the object lays just on the edge between the polygons

**Comment by tabeckers** [comment]
> There is a very unlikely possibly for an object to be not selected by the otherwise corresponding district. 

My previous comment does not suggest that buildings will be missed, but that buildings will exist in more than one district. Will this be a problem @yorickdewid?

**Comment by tabeckers** [comment]
This issue was split into itself and #214 because creating the foreign keys for the building table is something different than migrating data.

**Comment by yorickdewid** [comment]
Missing provinces and states in the geocoder, see #222
