### ISSUE TITLE
Move materialized views for BAG latest from public schema to data schema.

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMaps#215]
The following materialized views have to be moved and recomputed:

- [ ] `public.ligplaats_latest`
- [ ] `public.nummeraanduiding_latest`
- [ ] `public.openbareruimte_latest`
- [ ] `public.pand_latest`
- [ ] `public.standplaats_latest`
- [ ] `public.verblijfsobject_latest`
- [ ] `public.woonplaats_latest`

The following functions have to update their references to these materialized views: 

- [ ] `geocoder.fill_address()`
- [ ] `geocoder.fill_building()`

**Comment by tabeckers** [comment]
It might be better to completely remove these materialized views, as they have a dependency on their corresponding public BAG tables. The computation that they perform can be done with a filter, and since database performance is less of a problem we will not be needing these views. 

Agreed @yorickdewid ?

**Comment by yorickdewid** [comment]
Why do we need these views anyway?

**Comment by tabeckers** [comment]
The BAG contains multiple entries per bag-id. These views filter the BAG dataset to only return the most recent row for each bag-id, hence the name *_latest. We can simply migrate this to the queries that process the BAG dataset. 

Agreed?

**Comment by tabeckers** [comment]
Wont fix, see #345. These tables and materialized views will be removed.
