### ISSUE TITLE
Organization admin controller getAll, delete actions

### ISSUE THREAD

**Issue by yorickdewid** [Laixer/FunderMaps#236]
List all organizations in the application. Only administrators can request this information.

**Comment by tabeckers** [comment]
Some xml comments are missing.
The controller performs the mapping functionality. Wouldn't you want to build a service that does this?

**Comment by yorickdewid** [comment]
What would be the additional use for a mapping service?

**Comment by tabeckers** [comment]
For completeness. This has been discussed in person, no further action will be taken.
