### ISSUE TITLE
BAG and CBS contain invalid geometries

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMaps#260]
The following geocoder tables contained invalid geometries:
- [x] `building` _(2x)_
- [x] `district` _(1x)_
- [x] `neighborhood` _(1x)_
- [x] `municipality` _(1x)_
- [x] `state` _(2x)_
All invalid geometries were updated with their restored variant using `st_makevalid(geom)`. The problem lies in the data sources themself. We should take this into consideration next time we import any data.

**Comment by yorickdewid** [comment]
Add this to the data cleaning step when processing external data
