### ISSUE TITLE
Report Type

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#27]
Selecting report type "aanvullend onderzoek" isnt stored in DB. After save ("volgende"), go bank ("vorige") and report type is empty.

Selecting "second opinion" gives 500.

![image](https://user-images.githubusercontent.com/46600362/67079108-e0c46f80-f192-11e9-89da-1f77a3f016b6.png)

**Comment by yorickdewid** [comment]
Typo in database type, fixed
