### ISSUE TITLE
Reporttype "aanvullend onderzoek" isn't shown

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#28]
Step 1 add report; reporttype "aanvullend onderzoek" isn't shown but it is send to DB (shown at overview, step 3)

![image](https://user-images.githubusercontent.com/46600362/67162861-c17f3b00-f368-11e9-8bbe-11c96d56dec5.png)

**Comment by yorickdewid** [comment]
Frontend issue, it is shown, processed and saved. When editing a report the type is not set to the previously selected option.
