### ISSUE TITLE
Report download

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#30]
Report isn't downloading

![image](https://user-images.githubusercontent.com/46600362/67182093-aa7b3000-f3de-11e9-8c74-d428d54cbc1a.png)

**Comment by yorickdewid** [comment]
Frontend sends the wrong file name. For now this should be fixed in the frontend but the logic needs to move to the backend entirely

**Comment by yorickdewid** [comment]
Imrpovement: API sends 404 when file was not found in storage

**Comment by DonZandbergen** [comment]
New reports are now availeble.
