### ISSUE TITLE
Deleting a user which is currently pending as reviewer crashes the API

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMaps#314]
When a user exists in the `attribution` table because he or she was requested for review, a delete is no longer possible. When we attempt to delete said user the backend returns error code `500`.

**Comment by tabeckers** [comment]
Conclusion: Report should be re-set to pending and the user should be removed.

**Comment by yorickdewid** [comment]
When a user is removed thats been referenced in another table, a 404 is returned. Thats good enough for now.
