### ISSUE TITLE
No indexing can be used when using application.is_geometry_in_fence(user_id, geom)

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMaps#317]
A function is treated as a black box by postgresql. The only reason for the existence of this function is that our organization fence can be null at the moment. Simply using the `st_intersects(fence, geom)` function speeds up performance by an insane amount because indexing can be used.

**Note: the building geometry wasn't indexed so this statement might not be true. An index has been created.**

**Comment by yorickdewid** [comment]
Good call
