### ISSUE TITLE
Cleanup BAG for  Minucipality Amsterdam

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#331]
The municipality of amsterdam has no buildyear available for some of the historic buildings.
These are shown in the BAG with buildyear  "9999" and "1005".

Source:
https://www.amsterdam.nl/stelselpedia/bag-index/baten-bag/afleiden-bouwjaren/

Correct these years of construction. Most likely buildyear between: 1800-1970

**Comment by yorickdewid** [comment]
Why is this closed?

**Comment by DonZandbergen** [comment]
> Why is this closed?

Was a double entry

**Comment by tabeckers** [comment]
With regards to the **production** database:

All entries in the municipality of Amsterdam which had built_year set to **1005-01-01** have been updated to **1800-01-01**.
All entries which have **null** as their built_year have not been modified at this moment.
