### ISSUE TITLE
Buildingyear should not be obligated

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#388]
Het bouwjaar is nu verplicht in de database. Deze moet niet verplicht zijn.  Het bouwjaar wordt alleen ingevuld wanneer deze is opgegeven in de rapportage. Deze kan afwijken van het BAG bouwjaar.

![image](https://user-images.githubusercontent.com/46600362/98939733-2ebcbb80-24ea-11eb-932c-3e93cdffeebf.png)

**Comment by yorickdewid** [comment]
See #203
