### ISSUE TITLE
Pop-up in map

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#419]
In de pop-up bij de kaartweergave moeten voor de volgende lagen een link worden opgenomen naar de rapportage waarin de sample is vastgelegd. 

**Lagen waarbij de link moet worden opgenomen:**

- Funderingstype vastgesteld
- Rapport
- Kwaliteit
- Handhavingstermijnen
- Oorzaak schade

**Uitgangspunten:**

- Wanneer er meerdere rapporten een adres beschrijven, alle linken opnemen
- Links open in new window

**Comment by yorickdewid** [comment]
Backend + db work done
