### ISSUE TITLE
Hiërarchie data kaart Funderingstype vastgesteld

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#435]
De laag “Funderingstype vastgesteld” dient als volgt te worden opgebouwd met de sample data foundation type. Het laagste nummer van de voorwaarde waaraan voldaan wordt heeft de hoogste prioriteit en dient altijd weergegeven te worden:

1. Indien fundering hersteld "foundation recovery type"
2. Rapport bij sample betreft een “funderingsonderzoek”
2. Rapport bij sample betreft een “Bouwkundig”
3. Rapport bij sample betreft een “Archiefonderzoek”
4. Rapport bij sample betreffen de overige type rapporten.

Indien er meerdere samples voldoen aan de  voorwaarde geldt de sample met de meest recente report_date (let op: niet create or updated)

**Comment by yorickdewid** [comment]
`PARTITION BY foundation_type`

**Comment by DonZandbergen** [comment]
Indien uit funderingsonderzoek het type onbekend is geldt dat andere rapport vormen een hogere prioriteit moeten kringen.
Indien die er niet zijn moet de waarde van de indicatieve laag NIET worden uitgefilterd..
