### ISSUE TITLE
API product 7 aanpassen

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#437]
**Toevoegen** 

- Postcode toevoegen: “postal”
- Bron bouwjaar (BAG of FM): constructionYearScource””
- Woonoppervlak (BAG): “livingSurfaceArea”
- Onderbouw: “substructure”
- Herstel geadviseerd: “recoveryAdviced”
- Schade oorzaak: “foundationDamageCause”
- Betrouwbaarheid funderingsherstel: “recoveryStatus”

**Comment by yorickdewid** [comment]
`Woonoppervlak` is `SurfaceArea` ? Already part of API 7

**Comment by DonZandbergen** [comment]
Surface Area was oppervak van polygoon = oppervlakte begane grond
