### ISSUE TITLE
ANALYSE: Indicative Foundation type

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#46]
If no sample:foundation_type available then: 

- (BAG:built_year < 1970) = Wood
- (BAG:built_year > 1970 & <1980) = Wood/concrete
- (BAG:built_year > 1980) = Concrete

Legend (control value/legend tag/color in map):

- Wood  “Hoge kans op houten paal” = #9e511f
- Concrete  “Zeer hoge kans op beton paal”= #7A7A7A
- Wood/concrete  “Kans op houten paal en betonpaal” = #A860A6

A distinction should be made for the foundationtype based on sample-data and the indicative foundation type based on building year.  Sugestion: The foundation type based on BAG data should have a visible yellow boundary (outline of the object).
 
Deze kaartlaag moet samengevoegd worden met de kaart van funderingstype vastgesteld (sample data).

**Comment by yorickdewid** [comment]
For all current and future items?

**Comment by DonZandbergen** [comment]
Yes, should be dynamic. When a foundation_type is deleted from samples the indicative foundation type should be visuable. When a foundation_type is added to the sample data this should overwrite the indicative value.

Other discrepancies that are goining to encounterd (for insight at this point, these are new issues):
- 2 different foundation type values in the sample database for the same adress: most recent is applicable
- Buildings built together with the same year of construction (BAG: building_year) may deviate as indicative values ​​from values from the database. The values ​​from the database must count more heavily in the allocation of the idicative value. The algorithm must be expanded for this. This also takes into account the surface and height of buildings (AHN).
