### ISSUE TITLE
Http context race condition in dispatch manager

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMaps#479]
Sometimes when we dispatch a background task which requires an appcontext, a race condition occurs. The background task is created at line `154` of the `DispatchManager`:

`var backgroundTask = serviceScope.ServiceProvider.GetRequiredService(taskBucket.TaskType) as BackgroundTask;`

The dependency injector then calls the `AspAppContextFactory.Create()` method. This method returns the following app context object at line `66`, where `new()` refers to a `Core.AppContext` object:

```
return new()
{
    CancellationToken = httpContext.RequestAborted,
    Items = requestItems,
};
```

As we can see, the `httpContext.RequestAborted` object is called. The `HttpContext` object is obtained from the `IHttpContextAccessor.HttpContext` property. The problem is that the `IFeatureCollection` of this `HttpContext` object can already be disposed (race condition). Apparently the `RequestAborted` object, which is of type `CancellationToken`, resides somewhere in this `IFeatureCollection`. An exception is thrown.

A possible solution could be to used lock free lists.

Full logs:
```
fundermaps-app-prod 2021-02-16T10:25:37.406956518Z ESC[41mESC[1mESC[37mcritESC[39mESC[22mESC[49m: FunderMaps.Core.Threading.DispatchManager[0]
fundermaps-app-prod 2021-02-16T10:25:37.407013602Z       Exception when creating task
fundermaps-app-prod 2021-02-16T10:25:37.407018838Z       System.ObjectDisposedException: IFeatureCollection has been disposed.
fundermaps-app-prod 2021-02-16T10:25:37.407022889Z       Object name: 'Collection'.
fundermaps-app-prod 2021-02-16T10:25:37.407040513Z          at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed()
fundermaps-app-prod 2021-02-16T10:25:37.407044932Z          at Microsoft.AspNetCore.Http.DefaultHttpContext.get_RequestAborted()
fundermaps-app-prod 2021-02-16T10:25:37.407577761Z          at FunderMaps.AspNetCore.Components.AspAppContextFactory.Create() in /source/src/FunderMaps.AspNetCore/Components/AspAppContextFactory.cs:line 66
fundermaps-app-prod 2021-02-16T10:25:37.407596696Z          at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
fundermaps-app-prod 2021-02-16T10:25:37.407601986Z          at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
fundermaps-app-prod 2021-02-16T10:25:37.407929731Z          at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
```

**Comment by yorickdewid** [comment]
Likey solved
