### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by yorickdewid** [Laixer/FunderMaps#5]
Write integration tests for the `FunderMaps.Backend`. Test coverage on the API interface should approach 100%. The `FunderMaps.Backend` does not need other unit tests. The core logic is mostly covered in unit tests. We can extend the same idea to the `FunderMaps.Webservice` project. There should be a single assembly for all integration tests, or at least so far as possible.

- [x] Entity faker for core entities
- [x] Entity faker for DTOs
- [x] Datastore framework for offline testing
- [x] Authentication framework for local testing
- [x] Backened Application Tests
- [x] Backened Geocoder Tests
- [x] Backened Report Tests

**Comment by tabeckers** [comment]
This has been discussed many times, and has been cleaned up in #272
