### ISSUE TITLE
Add descriptions to webservice

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#501]
The IDescriptionService should be implemented and tested.
Depends on #225

Add descriptions to webservice. 

Regarding endponts:

- descriptionDrystand
- descriptionDewateringDepth
- descriptionBioInfection

**[[descriptionDrystand]]​**
[Risico op droogstand; laag]​
Er komt doorgaans geen droogstand voor. Er is een veilige marge van [[drystand]] m dat het grondwater hoger staat dan het hoogstgelegen funderingshout. Hierdoor kan het funderingshout niet rotten door een tekort aan zuurstof.  ​

[Risico op droogstand; midden]​
Er kan een droogstand van ca. [[drystand]] m van het hoogstgelegen funderingshout voorkomen maar deze bevindt zich doorgaans in een acceptabele marge. Bij wijzigende omstandigheden kan de situatie verergeren waardoor het funderingshout regelmatig droog kan komen te staan en het hout kan gaan rotten.  Na jarenlange droogstand kan het draagvermogen van de fundering zijn aangetast waardoor het pand kan gaan deformeren.  Indien dit in vergevorderd stadium is, zijn er scheuren in de gevel zichtbaar, klemmen ramen en deuren en vertoont het gevelaanzicht tekenen van verzakkingen.​

[Risico op droogstand; hoog]​
Er kan een droogstand van ca. [[drystand]] m van het hoogstgelegen funderingshout voorkomen. Hierdoor kan het funderingshout regelmatig droog komen te staan waardoor het hout kan gaan rotten.  Na jarenlange droogstand kan het draagvermogen van de fundering zijn aangetast waardoor het pand kan gaan deformeren. Indien dit in vergevorderd stadium is, zijn er scheuren in de gevel zichtbaar, klemmen ramen en deuren en vertoont het gevelaanzicht tekenen van verzakkingen.

**[[descriptionDewateringDepth]]​**
[Risico op tekort aan ontwateringsdiepte; laag]​
De gemiddelde grondwaterlevelfluctuatie is [[dewateringDepth]] m. Bij deze waarden is de kans op verzakkingen van een fundering op staal bij de ondergrond die bestaat uit [[soil]] laag.​

[Risico op tekort aan ontwateringsdiepte; midden]​
De gemiddelde grondwaterlevelfluctuatie is [[dewateringDepth]] m. Bij deze waarden is de kans op verzakkingen van een fundering op staal bij de ondergrond die bestaat uit [[soil]] gemiddeld.​

[Risico op tekort aan ontwateringsdiepte; hoog]​
De gemiddelde grondwaterlevelfluctuatie is [[dewateringDepth]] m. Bij deze waarden is de kans op verzakkingen van een fundering op staal bij de ondergrond die bestaat uit [[soil]] verhoogd.

**[[descriptionBioInfection]]**
[Risico op bacteriële aantasting; laag]​
Toepassing van grenen palen is hoogstwaarschijnlijk niet toegepast bij dit adres gelet op de diepteligging van de draagkrachtige zandlaag. Deze ligt dieper dan 10 m onder het maaiveld. Grenen palen zijn zelden langer dan 10 m. Toepassing is daarmee onwaarschijnlijk.​

[Risico op bacteriële aantasting; midden]​
Toepassing van grenen palen kan voorkomen bij dit adres gelet op de diepteligging van de ondiepe draagkrachtige zandlaag. Grenen palen zijn zelden langer dan 10 m. Grenen palen zijn gevoelig voor bacteriële aantasting waardoor het hout van buitenaf wordt aangetast over de gehele lengte van de paal. Het draagvermogen van de paal neemt daarmee af waardoor het pand gaat verzakken. Indien dit in vergevorderd stadium is, zijn er scheuren in de gevel zichtbaar, klemmen ramen en deuren en vertoont het gevelaanzicht tekenen van verzakkingen.​

[Risico op bacteriële aantasting; hoog]​
Grenen palen zijn hoogstwaarschijnlijk toegepast bij dit adres, gelet op de diepteligging van de ondiepe draagkrachtige zandlaag en het bouwjaar. Grenen palen zijn zelden langer dan 10 m. Grenen palen zijn gevoelig voor bacteriële aantasting waardoor het hout van buitenaf wordt aangetast over de gehele lengte van de paal. Het draagvermogen van de paal neemt daarmee af waardoor het pand gaat verzakken. Indien dit in vergevorderd stadium is, zijn er scheuren in de gevel zichtbaar, klemmen ramen en deuren en vertoont het gevelaanzicht tekenen van verzakkingen.

**Comment by yorickdewid** [comment]
Link to the description service issue
