### ISSUE TITLE
BAG panden ontbreken

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#504]
Er ontbreken hele delen van BAG panden in Haarlem.
In nagenoeg alle gevallen zijn al deze panden aan elkaar gekoppeld.

![image](https://user-images.githubusercontent.com/46600362/110162776-78aa1400-7def-11eb-95de-f8492fb74647.png)

Betreft ondermeer deze adressen:
adriaan loosjesstraat 60 0392100000005605
adriaan loosjesstraat 62 0392100000005606
adriaan loosjesstraat 64 66 
alberdingk thijmstraat 2 38 
Barendsestraat 33 49  
Barendsestraat 53 0392100000033648
Barendsestraat 55 59  
Bisschop ottostraat 1 37 
Bisschop ottostraat 2 38
Busken huetstraat 1 43 
Busken huetstraat 2 38 
De clercqstraat 103
Diederikstraat 1 25
Dr schaepmanstraat 2 
Koninginneweg 32 0392100000018506
Korte poellaan 17 21 
Kruistochtstraat 10 64 
Kruistochtstraat 11 59 
Linschotenstraat 53 0392100000034393
Potgieterstraat 3 11 
Tetterodestraat 77 

@DonZandbergen Daarna panden als hersteld toevoegen aan geopackage, combineren met oude layer met herstelde funderingen en opnieuw verwerken in FM.

**Comment by yorickdewid** [comment]
In order to verify the the issue list some of the missing BAG id's

**Comment by DonZandbergen** [comment]
> In order to verify the the issue list some of the missing BAG id's

see list.....

**Comment by yorickdewid** [comment]
Do not exist in current database

**Comment by pnobbe** [comment]
Database has been updated with new BAG dataset.

**Comment by DonZandbergen** [comment]
De check op is_active kotm uit de BAG 1.0
Dat is voor de ABG 2.0 niet meer juist.

Graag lijst geven van alle voorkomende statussen van de panden.
@DonZandbergen geeft aan welke statussen op kaart getoond moeten worden.
Wel de volledige BAG inladen, ook gegeven op oude panden moeten kunnen worden ingevoerd.
