### ISSUE TITLE
Delete buildings form recovery

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#534]
**Delete these buildings for recovery as they are are NOT recovered**

gfm-355910e5564041839c4a1c25e7e75758
gfm-e9ab8eb84b724dd0aa59bcbbb0aab9ac
gfm-6cc6b9b9bc5b4bd0823230544f20824f
gfm-32afa360ddae42a2aaa3d7410d70ec90
gfm-2830411817cc47f7995fb8bdd696a43a
gfm-d812520200804644b989592d5a6c18eb
gfm-1c1c96f756a24d86bdd06ce9ceb01f62
gfm-a412099cdfc4448e8150afcc6babbcd9
gfm-97692426bf4b45b0bc501c39cfafed16
gfm-fe0af763b9e04540b7560e3d8da21c9c
gfm-8fd67b621e394f0481fa0f76e3ba2d57
gfm-609137a7cce44ceea7617d7d7ab41ddb
gfm-34efcff95310437eb11575577333da51
gfm-00bc1ce84378427480e79abeec7e6a39
gfm-58c1844987a647ff86f4bb54c2d7f7f3
gfm-cccba91fbcb64442be19aa42757f1c53
gfm-b48df8f0cd374d82ba739ef8f12b312f
gfm-8d53ecb15cde42f8b16b6032c80ca1ce
gfm-dc2d5a7f52c94cb6a102f4226b1c1c13
gfm-02da1fadecb9409b9c828709361ff08e
gfm-3fd79a84881844f6aa1d882f3611fd64
gfm-e2696c7eceac467692846be74b778ebb
gfm-23e92627a192439c89d6b4a2287612b9
gfm-36992dd5aca7438694f0e6539a93a76d

**Comment by yorickdewid** [comment]
This may have gone wrong
