### ISSUE TITLE
Adjust model wood_charger

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#554]
In the model for determining the **foundation type indicative**, a precondition is that for the determination of buildings on wood_charger the builtyear  is between 1925 and 1970. The 1925 needs to be adjusted to 1920.

This should probably also be adjusted in the model for risk.

![script aanpassen](https://user-images.githubusercontent.com/46600362/117511586-456e3780-af8e-11eb-855b-84cd8105829d.PNG)

**Comment by yorickdewid** [comment]
Need more information

**Comment by DonZandbergen** [comment]
The image was a placeholder.
It may be wise to do this together in person to avoid mistakes.
