### ISSUE TITLE
Pandzakkingsdata inlezen

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#570]
Account: c374aa23-62d4-4047-b052-a7426f0d571a
Pandzakkingsdata inlezen: https://laixer.sharepoint.com/:u:/s/FunderMaps/ET57CnU3z6ZKhBcyF6QZYkYBiOsm1NrenuoUUojhHceFwQ?e=Jj4lGH

**Comment by yorickdewid** [comment]
Check
