### ISSUE TITLE
Add recovery

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#571]
Add recovery (type "unknow", status "establileshed") to account: 42aebd4c-20b2-45f9-8c7f-360047a9b7af
CSV: https://laixer.sharepoint.com/:f:/s/FunderMaps/EqmslRGuSWlLkd7FQkiInvABaqhdEbZcDgUKexsN9U-zzQ?e=7SqbRN

And delete recovery on building: 0392100000031355

**Comment by yorickdewid** [comment]
Delete recovery for building `NL.IMBAG.PAND.0392100000031355`

**Comment by yorickdewid** [comment]
Check
