### ISSUE TITLE
Add foundationtype to report

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#576]
Organisation: c96e7b54-63ce-4017-82a1-dcdec054bfd1
CSV:https://laixer.sharepoint.com/:f:/s/FunderMaps/Ej2jwfQBb0hNoMTYYawZI4sBoYAK1eqLWn9mICM3xtSK2Q?e=pLDpQn

Add report tot organisation, then add foundation_type.

**Comment by yorickdewid** [comment]
Check
