### ISSUE TITLE
Upload samples foundation_recovery

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#675]
- Samples recovery upload to account: ef7716d-e69a-11ec-b1dc-0c42a19a82a7
- Linked report: in sharepoint:.
- CSV with samples :  in sharepoint:
-  SharePoint folder: https://laixer.sharepoint.com/:f:/s/FunderMaps/EswkezL5USlAt7B9j3AtgOQBKEWpT0ebhJmFP3cafTKGVg?e=0zenXQ
- Column is CSV: fid,building_id,external_building_id,address_id,address_external_id,recovery_type
- Recovery_type values (CSV - Table) : "table"= "table", "partial" = "partial".

**Comment by yorickdewid** [comment]
Account bestaat niet

**Comment by DonZandbergen** [comment]
Account FunderMaps
