### ISSUE TITLE
Salpes-page meer-links services

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#705]
(1) Applicatie:
Efficiënte data-invoer en rapportgeneratie. Een intuïtieve SaaS-oplossing voor het verwerken van onderzoeks- en archiefgegevens van funderingen en panden. Naadloze integratie met F3o-onderzoeksrichtlijnen, vergemakkelijkt het invullen van uw database en genereert PDF-rapporten.

(2) Modellen:
Betrouwbare inzichten met geavanceerde AI-modellen. Betrouwbare voorspellingen voor het funderingstype en -risico's wanneer deze niet bekend zijn. Deze inzichten helpen weloverwogen vastgoed- en funderingsbeslissingen te nemen.

(3) Kaartviewer:
De kaartviewer visualiseert cruciale funderingsdata, waaronder funderingstypes, herstelde funderingen, schouwgegevens en funderingsrisico's. Door gebruik te maken van diverse databronnen en automatische dagelijkse updates, heeft u altijd toegang tot actuele informatie.

(4) API:
Directe toegang tot waardevolle funderingsdata via de krachtige API. Deze API verhoogt de efficiëntie en productiviteit van uw organisatie door up-to-date en nauwkeurige funderingsinformatie altijd binnen handbereik te hebben.

Voorbeeld (en hup nu)
![image](https://github.com/Laixer/FunderMaps/assets/46600362/67ec234d-4009-4d57-a072-4ac7d37ef274)

**Comment by yorickdewid** [comment]
Teksten moeten veel kleiner, 1 a 2 regels

**Comment by DonZandbergen** [comment]
Niet volgens ChatGPT

**Comment by DonZandbergen** [comment]
Aangepaste teksten volgen

**Comment by DonZandbergen** [comment]
Gebruik de FunderMaps applicatie, een intuïtieve SaaS-oplossing voor het verwerken van onderzoeks- en archiefgegevens van funderingen en panden. Deze tool biedt naadloze integratie met onderzoeksrichtlijnen, vergemakkelijkt het invullen van uw database en genereert PDF-rapporten, ideaal voor instanties die efficiënt willen werken met betrouwbare panddata.
