### ISSUE TITLE
Add damagecause types to incident/UI

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#731]
UI: Grondwaterstandsverlaging
DB: groundwatertabellowering

**Comment by yorickdewid** [comment]
Fixed after deploy

**Comment by DonZandbergen** [comment]
De toegevoegde schade oorzaak aan de woning (Grondwaterstandverlaging) is correct toegevoegd in de front-end. Het komt goed door in de e-mail en komt goed in de tabel (grafana: groundwater_level_reduction).

**Comment by DonZandbergen** [comment]
Deze bug gevonden tijdens deze test: https://github.com/Laixer/FunderMaps/issues/798
