### ISSUE TITLE
Test results bughunt Numeric overflow

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#749]
Bouwjaar groter current?
- UI vindt het goed, servergeeft 500

Deze attributen mogen [5,2] zijn.
Bij [6,2] vindt de UI het goed maar geeft de server 500
- pileDiameterBottom
- pileDiameterTop
- concreteChargerLength
- pileDistanceLength 
- woodLevel
- groundlevel
- masonLevel
- groundwaterLevelTemp
- groundwaterLevelNet
- cracks (all variants)

woodPenetrationDepth mag [3,0] zijn.
Bij [3,1] vindt de UI het goed maar geeft de server 500

Ik denk echter dat numeric overflow het masonLevel (NIVEAU ONDERKANT METSELWERK) is. Die wordt op geslagen als string zo te zien. Dat zal de database niet goed vinden

Voor de verdere duidelijkheid moet er bij de numerieke velden bij wat de eenheid is:

- pileDiameterBottom (tooltip maken "mm")
- pileDiameterTop (tooltip maken "mm")
- concreteChargerLength (tooltip maken "m")
- pileDistanceLength (tooltip maken "m")
- woodPenetrationDepth (tooltip maken "mm")
- woodLevel (tooltip maken "m t.o.v. NAP")
- masonLevel (tooltip maken "m t.o.v. NAP")
- groundlevel (tooltip maken "m t.o.v. NAP")
- groundwaterLevelTemp (tooltip maken "m t.o.v. NAP")
- groundwaterLevelNet (tooltip maken "m t.o.v. NAP")

**Comment by yorickdewid** [comment]
Volgende velden hebben een limit (0-999.99) gekregen in de backend validator:

- GroundwaterLevelTemp
- GroundLevel
- GroundwaterLevelNet
- ConstructionLevel
- WoodLevel
- PileDiameterTop
- PileDiameterBottom
- PileHeadLevel
- PileTipLevel
- FoundationDepth
- MasonLevel
- ConcreteChargerLength
- PileDistanceLength
- WoodPenetrationDepth
- ThresholdFrontLevel
- ThresholdBackLevel
- SkewedParallel
- SkewedPerpendicular

Dezelfde velden hebben ook een frontend validator.

Controlleren/testen:

- Bouwjaar loopt van 901-2100
- foundationDepth bestaat wel in de backend/database, niet in de frontend
- woodPenetrationDepth was text in de frontend, maar numeric in de backend/database

**Comment by DonZandbergen** [comment]
Controlleren/testen: 
Bouwjaar loopt van 901-2100 = Done
woodPenetrationDepth was text in de frontend, maar numeric in de backend/database = Done

**Comment by yorickdewid** [comment]
Nieuwe issue maken voor veranderen datatype crack size van decimal naar integer

**Comment by DonZandbergen** [comment]
foundationDepth bestaat wel in de backend/database, niet in de frontend

=> NIVEAU ONDERKANT FUNDERINGSBALK (bij kopje Niveau & Kwaliteit) WANNEER het foundationType = variant van noPile dan betereft het de foundationDepth  die ingevuld moet worden.


De keuze FUNDERINGSBALK   en   KWALITEIT FUNDERINGSBALK  is dan niet zichtbaar:
![image](https://github.com/Laixer/FunderMaps/assets/46600362/0fc0dfc1-3911-47a5-940f-3c4ebe029595)

Het veld heet dan ipv NIVEAU ONDERKANT FUNDERINGSBALK => FUNDERINGSNIVEAU.
