### ISSUE TITLE
Conditions map generation

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#755]
Voorwaarden voor genereren nieuwe tilsets:

**Na 50 nieuwe samples maar maximaal 1x/24uur**
•	analysis_foundation
**Na 50 nieuwe samples maar maximaal 1x/7dagen**
•	analysis_report
•	analysis_risk
•	analysis_building
**Na ieder nieuw rapport met inquiry_type = ‘ facade_scan’** 
•	facade_scan
**Na ontvangen van 1 incident die volgende nacht maken van deze tilesets, maximaal 1x/24uur**
•	incident_district
•	incident_neighborhood
•	incident_municipality
**Vervallen/verwijderen**
•	analysis_monitoring

Mogelijkheden voor parameters over locatie en gebruikers bewust niet meegenomen. Evenals de 50 samples te laten bepalen door gemiddeld gebruik.

Wanneer kaarten getriggerd worden te maken moet wel duidelijk blijven. Wellicht datum kaart opnemen in kaart.

**Comment by yorickdewid** [comment]
Implementation done, should test in next days
