### ISSUE TITLE
Registreren nieuwe gebruikers

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#766]
Registreren nieuwe gebruikers is niet mogelijk op organisatie pagina:
https://app.fundermaps.com/organization

Server geeft 405.

![image](https://github.com/Laixer/FunderMaps/assets/46600362/e696ec10-cb9a-4535-b19f-f9b32aeba5bf)

**Comment by yorickdewid** [comment]
Backend function does not exist anymore. Not a bug, just not implemented

**Comment by DonZandbergen** [comment]
Oke. Dan handmatig toevoegen voorlopig.
