### ISSUE TITLE
Generate CSVs once a month for all WS customers

### ISSUE THREAD

**Issue by yorickdewid** [Laixer/FunderMaps#772]
**Requirements:**

- [x]  On the 1st day of each month, create a new CSV file for each account that made a call to a webservice summarizing all the calls from the previous month.
- [x] Each CSV file should be specific to a account.
- [x]  Include the following information in each CSV:
  - BAG.Pand.ID
  - Requested ID
  - Date+time
  - Product requested

- [ ] For some clients, we need to identify mutations (changes) in the data. To do this, compare the new CSV with the previous month's CSV. If there are differences in information between the two, mark it as a mutation.
- [ ] If possible, implement a function to automate the comparison process. If not, manual comparison will be required.
- [ ] If manual comparison is necessary, add the results from "webservice production analysis" information to each call in the CSV to assist with the comparison.

**Comment by DonZandbergen** [comment]
Add NL.IMBAG.PAND id.

**Comment by yorickdewid** [comment]
Done
