### ISSUE TITLE
Total Gepackage

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#775]
Voor intern gebruik is er behoefte aan een totale Geopackage met alle OF minimaal onderstaande attributen:

- BAGPAndID
- reportID
- building_id
- district_id
- municipality_id
- neighborhood_id
- address_count
- construction_year
- construction_year_reliability
- owner
- organisation (eigenaar document = account)
- height
- inquiry_type
- overall_quality
- damage_cause
- enforcement_term
- foundation_type
- foundation_type_reliability
- recovery_type
- velocity
- restoration_costs
- bio_infection_risk
- bio_infection_risk_reliability
- dewatering_depth
- dewatering_depth_risk
- dewatering_depth_risk_reliability
- drystand
- drystand_risk
- drystand_risk_reliability
- unclassified_risk

**Comment by yorickdewid** [comment]
Tileset `analysis_risk_full` includes all fields except for organization. The mapbundle tileset doesn't have a precondition so its scheduled to be build every night. GPKG is found in the spaces directory

**Comment by DonZandbergen** [comment]
- BAGPAndID (external BuildingId) and  IquiryID is missing

**Comment by yorickdewid** [comment]
Done
