### ISSUE TITLE
Inlezen owner

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#783]
2 x owner bestanden inlezen:

- \Laixer\FunderMaps - Documenten\Projects\2023-006 Woonkracht10\owner
- \Laixer\FunderMaps - Documenten\Projects\2023-0011 Var. Corpos\bastonwonen\owner

**Comment by yorickdewid** [comment]
![image](https://github.com/Laixer/FunderMaps/assets/7712841/2341a8b4-eda7-4901-bae9-08f4a2dc27b8)

**Comment by yorickdewid** [comment]
2 de file 0 matches

**Comment by DonZandbergen** [comment]
NL.IMBAG.PAND. is een verblijfsobject ID.
Dat klopt niet, heb ik aangepast in v1.1.

Inlezen op pc6+huisnummer

**Comment by yorickdewid** [comment]
![image](https://github.com/Laixer/FunderMaps/assets/7712841/f92e3490-8827-411c-83b5-8ccdf038bf5d)

**Comment by DonZandbergen** [comment]
> ![image](https://user-images.githubusercontent.com/7712841/274179685-f92e3490-8827-411c-83b5-8ccdf038bf5d.png)

niet meer relevant; verblijfsobject kan niet ingelezen worden.

**Comment by yorickdewid** [comment]
Er is niks anders op te matchen

**Comment by DonZandbergen** [comment]
> Er is niks anders op te matchen

PC6 en huisnummer?

**Comment by yorickdewid** [comment]
![image](https://github.com/Laixer/FunderMaps/assets/7712841/23378e74-4e2f-478d-8c7e-0add68a54bfb)

**Comment by DonZandbergen** [comment]
4501 (Woonkracht) klopt
625  Baston Wonen lijkt te kloppen
