### ISSUE TITLE
Webservice BUG

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#791]
**Recovery**
Het lijkt erop dat geen enkele herstelde fundering wordt meegegeven in WS analysis
Herstelde panden zitten wel in tilesets.

Voorbeelden (wel hersteld in tilesets, niet in WS):

- gfm-443710fe2eab4d42a2df579adfa5b4b6
- gfm-bd45d5580ea14df4a60256f50ebe6a3a
- gfm-5efa0300da6542aab61c5ffa4afa92ea

**Statistics**
De staistics geven geen waarden

**Comment by yorickdewid** [comment]
Analysis of statistics?

**Comment by DonZandbergen** [comment]
> Analysis of statistics?

Analysis

**Comment by DonZandbergen** [comment]
De analyse resultaten in de webservice (analysis) geeft geen herstelde panden  (recovery type) meer. Enkele testcase:
NL.IMBAG.PAND.0606100000011726
NL.IMBAG.PAND.0606100000015507

**Comment by DonZandbergen** [comment]
BUG nog aanwezig (getest via WS)
