### ISSUE TITLE
Export entire model as CSV every day

### ISSUE THREAD

**Issue by yorickdewid** [Laixer/FunderMaps#810]

**Comment by yorickdewid** [comment]
Implementation done, needs to be optimized not to use so much memory

**Comment by yorickdewid** [comment]
Limit service memory usage

**Comment by DonZandbergen** [comment]
![image](https://github.com/Laixer/FunderMaps/assets/46600362/464fa4fe-e9f5-4509-a5ba-d755db2ca973)
