### ISSUE TITLE
Upload pandzakkingsdata

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#813]
**Bron**: https://laixer.sharepoint.com/:u:/s/FunderMaps/ESHFQs9kopZPk1fu_1ajXIcB8x_Zoq3RyjfjWTd5UKJRDw?e=WpOgMZ
**BAGPAndID** = "identificatie"
**Zakkingsnelheid**: "pand_mean_linear" * 1000 (om van m/jaar naar mm/jaar te gaan)

**Comment by yorickdewid** [comment]
Inserted rows: 2886
