### ISSUE TITLE
DATA: Zakkingsgegevens Sdam

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#84]
Zakkingsdata in mm/jaar opnemen op pandniveau. Dit betreft een 1 gemiddelde waarden per pand. 

Er zijn 2 leveranciers: 

- SkyGeo, gebruikt TerraSarX
- Sensar, gebruikt RadarSatXF

Beide leveranciers leveren niet de bron-data (voor INSAR analyse)  en niet de meetdata (punten na INSAR). Wel wordt een laag geleverd met een zakkingssnelheid per pand. Dit betreffen verschillende statistische zakkingssnelheden. Uitgangspunt is dat de 25percentiel waarden 

**Data**
Data van Sensar voor Gemeente Schiedam/ SkyGeo voor Gemeente Rotterdam/ SkyGeo voor Gemeente Haarlem zijn opgenomen in de DATA map: : \fundermapsbv_projecten\DATA

**Toekomst**
De statistisch gemiddelde pandzakking wordt bepaald op basis van meetreeksen. Idealiter wil je die gehele meetreeks opnemen op pandniveau zodat je ook verschillende snelheden in de tijd kan meenemen. Dit behoort vooralsnog niet bij de leveringen.

![image](https://user-images.githubusercontent.com/46600362/70942626-5e034800-204f-11ea-900b-ffc1683130a6.png)

**Comment by yorickdewid** [comment]
Schiedam ingelezen

**Comment by yorickdewid** [comment]
Rdam data opleveren onder deze ticket of deze afronden en een nieuwe ticket maken voor rdam
