### ISSUE TITLE
Eigenaren toevoegen in Mapset "Gebouw" laag "Eigenaar".

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#844]
In Mapset "Gebouw" staat de laag "Eigenaar".
Die heeft de volgende items en kleuren (legenda):

1. Trivire #a1368e
2. Woonkracht10 #e00532
3. Woonbron #5a7c00
4. Accolade #ec6820
5. Elkien #d6005b
6. QuaWonen #008688
7. Baston #007abd
8. Overige corporaties #bfc5c3

Zie ook issue 1: https://github.com/Laixer/FunderMapsWebFront/issues/1

![image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/c2192923-6eb7-4ca0-9236-3523d089db8e)

**Comment by yorickdewid** [comment]
Dit moet uit de database komen.
