### ISSUE TITLE
Naam meldingloket is 0

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#845]
Naam meldingloket is weergeven, zie regel 126 in de excel.

![image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/fea23e48-c88c-4b7a-9985-326ede61d196)

**Comment by yorickdewid** [comment]
Dit moet uit de database komen, is nu niks voor.

**Comment by DonZandbergen** [comment]
@WvanDam Hoe wil je dit aangeleverd hebben? Via API via de Back-End?

**Comment by WvanDam** [comment]
Dit is toch een ENUM? Ik kopieer / vertaal die uit de API codebase. Als daar geen ENUM staat maak ik zelf iets adhv de Excel.

**Comment by yorickdewid** [comment]
Nee zeker geen enum, misschien hebben we dat wel laten vallen. Het is eigenlijk een string. Wil je dat ik die als string terugstuur?

**Comment by WvanDam** [comment]
ah. Was dit niet al clientId / clientName in de API? Ik had de interface en class uitgebreid met clientName, maar ik denk dat hier nog clientId wordt weergegeven omdat ik bij het maken van de componenten de lijstjes met weer te geven eigenschappen 1 op 1 vanuit de excel heb overgenomen en deze dus als uitzondering daar van af moet wijken.

**Comment by yorickdewid** [comment]
Je hebt gelijk: 
![image](https://github.com/Laixer/FunderMaps/assets/7712841/19b825a7-6d4c-4882-b21f-8aaa82195f56)

**Comment by WvanDam** [comment]
Fix is onderweg
