### ISSUE TITLE
Geo-fence

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#85]
Per organisatie dient een afkadering van het areaal (Geo-fence) ingesteld te kunnen worden. Een dergelijk areaal is opgebouwd op twee verschillende wijze:

- CBS Buurt/Gemeente/Provincie (voor bv Gemeentelijke opdrachtgevers)
of
- Vastgoedbezit van organisatie (Voor bv woningbouwcoorperaties)

Binnen een Geo-fence moet in de grafische ontsluiting (kaart) de aan een organisatieaccount gekoppelde data beschikbaar zijn. 

Data van andere organisatieaccounts kan een verrijking zijn voor andere organisatie accounts. Dit komt nu al voor: Organisatie Woonstad en organisatie Woonbron moeten voor hun areaal OOK de data van de Gemeente Rotterdam weergeven.

De geo-fences voor de huidige op te leveren projecten zijn hieronder benoemd.

Per organisatieaccount startpunt bij weergave kaart in midden van Geo-fence en zoom level 14 openen.

bepalen met: https://www.keene.edu/campus/maps/tool/

**Comment by DonZandbergen** [comment]
Woonbron: 

4.4553423, 51.9226466
4.4555140, 51.9136469
4.4604063, 51.9052544
4.4521236, 51.9032686
4.4481754, 51.9040365
4.4491196, 51.9099936
4.4374895, 51.9217732
4.4552565, 51.9226201
{
  "coordinates": [
    [
      [
        4.4553423,
        51.9226466
      ],
      [
        4.455514,
        51.9136469
      ],
      [
        4.4604063,
        51.9052544
      ],
      [
        4.4521236,
        51.9032686
      ],
      [
        4.4481754,
        51.9040365
      ],
      [
        4.4491196,
        51.9099936
      ],
      [
        4.4374895,
        51.9217732
      ],
      [
        4.4552565,
        51.9226201
      ]
    ]
  ],
  "type": "LineString"
}

**Comment by DonZandbergen** [comment]
**Haarlem, Rozenprieel:**


+
−
Leaflet | Imagery © Wikimedia
Polyline Tool
Import
Reset
Undo
Close Shape
4.6402001, 52.3769091
4.6357155, 52.3757695
4.6310806, 52.3758743
4.6305013, 52.3741320
4.6408010, 52.3714857
4.6431828, 52.3750228
4.6402645, 52.3767912
{
  "coordinates": [
    [
      [
        4.6402001,
        52.3769091
      ],
      [
        4.6357155,
        52.3757695
      ],
      [
        4.6310806,
        52.3758743
      ],
      [
        4.6305013,
        52.374132
      ],
      [
        4.640801,
        52.3714857
      ],
      [
        4.6431828,
        52.3750228
      ],
      [
        4.6402645,
        52.3767912
      ]
    ]
  ],
  "type": "LineString"
}

**Comment by DonZandbergen** [comment]
**Haarlem, Leidshenbuurt:**


+
−
Leaflet | Imagery © Wikimedia
Polyline Tool
Import
Reset
Undo
Close Shape
4.6291924, 52.3824104
4.6239138, 52.3770139
4.6145582, 52.3800266
4.6170902, 52.3841131
4.6292353, 52.3824628
{
  "coordinates": [
    [
      [
        4.6291924,
        52.3824104
      ],
      [
        4.6239138,
        52.3770139
      ],
      [
        4.6145582,
        52.3800266
      ],
      [
        4.6170902,
        52.3841131
      ],
      [
        4.6292353,
        52.3824628
      ]
    ]
  ],
  "type": "LineString"
}

**Comment by DonZandbergen** [comment]
**Gemeente Schiedam:**


+
−
Leaflet | Imagery © Wikimedia
Polyline Tool
Import
Reset
Undo
Close Shape
4.3545341, 51.9488148
4.3639755, 51.9339995
4.3701553, 51.8970457
4.4201088, 51.9014945
4.4116974, 51.9142028
4.4192505, 51.9239434
4.4084358, 51.9355871
4.3797684, 51.9545279
4.3545341, 51.9482857
{
  "coordinates": [
    [
      [
        4.3545341,
        51.9488148
      ],
      [
        4.3639755,
        51.9339995
      ],
      [
        4.3701553,
        51.8970457
      ],
      [
        4.4201088,
        51.9014945
      ],
      [
        4.4116974,
        51.9142028
      ],
      [
        4.4192505,
        51.9239434
      ],
      [
        4.4084358,
        51.9355871
      ],
      [
        4.3797684,
        51.9545279
      ],
      [
        4.3545341,
        51.9482857
      ]
    ]
  ],
  "type": "LineString"
}

**Comment by DonZandbergen** [comment]
**Poortvliet**

4.1543770, 51.5523662
4.1321898, 51.5519392
4.1318893, 51.5371534
4.1561365, 51.5368597
4.1543770, 51.5523662
{
  "coordinates": [
    [
      [
        4.154377,
        51.5523662
      ],
      [
        4.1321898,
        51.5519392
      ],
      [
        4.1318893,
        51.5371534
      ],
      [
        4.1561365,
        51.5368597
      ],
      [
        4.154377,
        51.5523662
      ]
    ]
  ],
  "type": "Polygon"
}

**Comment by DonZandbergen** [comment]
**Gemeente Roden**

6.4488029, 53.1563957
6.3867474, 53.1384815
6.4052010, 53.1174691
6.4724922, 53.1351861
6.4488029, 53.1563957
{
  "coordinates": [
    [
      [
        6.4488029,
        53.1563957
      ],
      [
        6.3867474,
        53.1384815
      ],
      [
        6.405201,
        53.1174691
      ],
      [
        6.4724922,
        53.1351861
      ],
      [
        6.4488029,
        53.1563957
      ]
    ]
  ],
  "type": "Polygon"
}

**Comment by DonZandbergen** [comment]
**Wetterskip:**

5.8618927, 52.8685080
5.8100510, 52.8187406
5.8790588, 52.7981949
5.9422302, 52.8342990
5.9281540, 52.8546203
5.8618927, 52.8685080
{
  "coordinates": [
    [
      [
        5.8618927,
        52.868508
      ],
      [
        5.810051,
        52.8187406
      ],
      [
        5.8790588,
        52.7981949
      ],
      [
        5.9422302,
        52.834299
      ],
      [
        5.928154,
        52.8546203
      ],
      [
        5.8618927,
        52.868508
      ]
    ]
  ],
  "type": "Polygon"
}

**Comment by yorickdewid** [comment]
Haarlem is 2x hetzelfde gebied

**Comment by yorickdewid** [comment]
Alleen gemeente Schiedam gedaan, rest heeft geen organisatie

**Comment by DonZandbergen** [comment]
Woonbron en Haarlem (reeds bestaand) hebben een account

![image](https://user-images.githubusercontent.com/46600362/71092651-f1e82780-21a7-11ea-892f-898687530595.png)

**Comment by DonZandbergen** [comment]
Woonborg en Wetterskip zijn aangemaakt

![image](https://user-images.githubusercontent.com/46600362/71093387-5eaff180-21a9-11ea-99e4-d50ec75632a2.png)

**Comment by DonZandbergen** [comment]
Projectgebieden Haarlem zijn aangepast

**Comment by DonZandbergen** [comment]
Gemeente Tholen toegevoegd

**Comment by DonZandbergen** [comment]
Data Rotterdam terug naar PRIVATE zodat niet alle andere account deze data te zien krijgt.

**Comment by DonZandbergen** [comment]
Alle organisatie accounts kijken naar de Geo-fence van account van Woonbron.
Hierdoor wordt geen sample data weergegeven van het betreffende account,
Hierdoor wordt voor de BAG-analyses (fundatie type indicatief en bouwjaar) bij aanvinken vanuit dropdown op de kaart de panden met analyses weergeven voor Woonbron.

**Comment by DonZandbergen** [comment]
https://geoman.io/geojson-editor
