### ISSUE TITLE
Missing data incidents

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#853]
Wanneer je op pand klikt is de incidents data niet bereikbaar terwijl die er wel is.

![Image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/87f7ebb3-cb35-4a43-9d19-b01a666bb4ec)

![Image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/d72d9a00-4f29-491b-ba11-0f65d6692024)

Enkele andere voorbeelden:

- Raam 4, 3011AH Rotterdam
- Claes de Vrieselaan 10bso, 3021JN Rotterdam

Situaties waar wel data wordt getoond:

- Brugweg 10, 2741 KX Waddinxveen, Nederland
- Beatrixlaan 2, 2811LX Reeuwijk

**Comment by WvanDam** [comment]
@yorickdewid https://maps.fundermaps.com/api/report/FIR622022-4196 geeft (voor mij en blijkbaar ook Don) lege arrays terug (edit: dit betreft het pand in Sneek in het 2de screenshot).

**Comment by yorickdewid** [comment]
Missing portals, in this example portal 62 is unknown.

@DonZandbergen
