### ISSUE TITLE
Zoom Buttons Disappear Behind Side Panel After F5 Refresh

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#864]
Problem Description:
When a user clicks on a property so that the right side panel appears, and then refreshes the page using the F5 key, the zoom buttons disappear behind the right side panel. This issue impedes access to the zoom functions, negatively impacting the user experience.

Steps to Reproduce the Issue:
1. Open the application and select a property.
2. Ensure the right side panel is visible.
3. Press the F5 key to refresh the page.

![Image](https://github.com/Laixer/FunderMaps/assets/46600362/ad17eb5e-7ae9-4117-999a-9ce26072c5a6)

**Comment by WvanDam** [comment]
Je was me net voor. De positioning check werd uitgevoerd net voordat de controls beschikbaar waren, en deed daarom niets. Deze check had ik geschreven voordat de sidebar vanuit de url open ging, en was nog ongetest. Het is nu gefixed.
