### ISSUE TITLE
Add Attributes to Analysis_Full Geopackage

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#872]
## Description
Include the following attributes in **Analysis_Full Geopackage** so they are available in the Geopackage and can be used in QGIS:

- contractor
- owner
- skewed_parallel
- facade_skewed_parallel
- skewed_perpendicular
- facade_skewed_perpendicular
- crack_type
- facade_risk

## Expected Behavior
The mentioned attributes should be available in the Geopackage and visible/usable in QGIS.

**Comment by yorickdewid** [comment]
Owner is included in the export

**Comment by yorickdewid** [comment]
Other fields are not part of the model
