### ISSUE TITLE
Enable multiple Geographic Boundaries for Organizations

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#875]
## Description
It should be possible for the admin to set one or more geographical areas as geographic boundaries (neighborhoods, districts, municipalities) for organizations, so that users can only see the relevant information in the map application. This feature will enhance the flexibility and usability of the application.

## Actions

- [x] Review the provided boundaries per account: [Boundaries per account](upload://file-wxH0FbF1wUct7dlw28OmVcFZ)
- [x] Update the database schema to store geographic boundaries for each organization.
- [ ] Modify the API to filter data based on the set geographic boundaries.
- [x] Implement logic in the map application to restrict data visibility according to geographic boundaries.
- [ ] Test the feature thoroughly to ensure correct functionality.

## Expected Behavior
Admins should be able to set geographic boundaries for organizations. Users should only see information relevant to their organization's specified boundaries in the map application.

## Additional Information
Refer to the link provided for detailed boundaries per account.
No design and implementation of a UI for admins is necessary. This can be executed from the command line as directed by the admin.

Relates to:https://github.com/Laixer/FunderMapsWebFront/issues/61

**Comment by yorickdewid** [comment]
All backend operations are done

**Comment by yorickdewid** [comment]
Frontend is capable of using multiple municipalities

**Comment by DonZandbergen** [comment]
Configuratie: https://laixer.sharepoint.com/:x:/s/FunderMaps/EXFPvSLyOcpNhe-EyS9F9xIB_pWD8j0vZeitK-TqQI7xzg?e=qQIyC1
