### ISSUE TITLE
Ensure GevelScans are Available to All Accounts with Appropriate Rights

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#892]
## Description
A GevelScan has been entered under account X in app.fundermaps.com. The map display of this data from the GevelScan is shown only shown in the account of KCAF on maps.fundermaps.com but not in maps.fundermaps.com for account X. An example can be found here: [GevelScan Example](https://app.fundermaps.com/inquiry/140004).

Entered GevelScans should be available for every account as long as they have the GevelScan mapset and the rights to view the data within the contour where the GevelScan falls.

## Actions

- [ ] Review the current visibility and permissions settings for GevelScan data.
- [ ] Ensure that GevelScan data is available to all accounts that have the GevelScan mapset and the rights to view the relevant contour.
- [ ] Update the map display logic to correctly show GevelScan data for all relevant accounts.
- [ ] Test the changes to confirm that GevelScan data is visible to all appropriate accounts.
- [ ] Deploy the updated visibility settings and map logic to maps.fundermaps.com.

## Expected Behavior
GevelScans entered in any account should be visible to all accounts that have the GevelScan mapset and the necessary rights to view the data within the relevant contour.

## Additional Information
Refer to the example GevelScan here: [GevelScan Example](https://app.fundermaps.com/inquiry/140139).

##Screenshots

![Image](https://github.com/user-attachments/assets/0392e81c-d042-4e07-aed4-79f43299cd90)

![Image](https://github.com/user-attachments/assets/2884783b-9350-4b7b-9753-b20733a9e3da)

**Comment by yorickdewid** [comment]
Mogelijk, maar een hoop werk. Is dit een one-off? Zoja dan kunnen we beter gevelscan toevogen aan de orgs zoals we dat met alle andere kaarten ook doen.
