### ISSUE TITLE
Sample data Gemeente Rotterdam

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#95]
Ongeveer 16000 adressen met sample data zijn NIET gekoppeld aan een adres van de BAG.
Daarmee is er geen match en kan de sample data gekoppeld aan die adressen niet worden ontsloten.

Voor de hand liggende redenen zijn vervallen straten, die geven geen match meer omdat ze in de huidige adressenlijsten niet meer voorkomen. Spelfouten in de straatnamen is een andere.

Dit kan verder gefilterd worden. Er zijn 2 categorieën:

- Spelfouten in namen (fuzzy matching kan een oplossingsrichting zijn)
- Straten en huisnummers komen niet meer voor maar hebben wel bestaan (historisch)

**Comment by tabeckers** [comment]
The data was analyzed and partially restored based on our geocoder.address table. The following matching techniques were used:

- If a streetname exists only in one city in our geocoder.address table, match it based on housenumber.
- If a streetname contains (rzb), we assume this to be the city of Rozenburg. Match accordingly.
- A Full Text Search was done for the rest of the rows, where the length of the streetname has to be the same in both tables. The building number was then compared (had to be exact), and the rows were matched.
