### ISSUE TITLE
Data deling

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMaps#98]
- Sample-data moet bij verschillende organisaties zichtbaar kunnen zijn.
- De verwerker blijft bronhouder maar sample data van organisatie A moet organisatie B helpen aan een beter inzicht.
- Organisatie B kan de data van een andere bronhouder niet bewerken
- Organisatie A krijgt alleen data te zien van andere organisaties binnen het areaal (geofence) van organisatie B

- De mogelijkheid voor een organisatie zelf moet er zijn om data PUBLIC of PRIVATE te zetten. Standaard is alles PUBLIC .

Case: Dit komt voor bij bijvoorbeeld een areaal van een woningsbouw corporatie (organisatie A) binnen een Gemeente (Organisatie B) waarbij de Gemeente meer data heeft dan de woningbouwcoorperatie.

Er is een relatie met #82

**Comment by DonZandbergen** [comment]
Issue heeft verduidelijking nodig

**Comment by yorickdewid** [comment]
Opsplitsing in meerdere losse issues
